### PR TITLE
Youtube Video Player Page Clone

### PR DESCRIPTION
**Pull request by pbkabali**
### Description of task
- Created a clone of the YouTube video Player page

### Screenshot

image

### CODE REVIEW

**Review by expjazz — CHANGES_REQUESTED** [review]
## Hey @pbkabali  and @t-yanick 

The project looks great at first sight, but unfortunately, it does not have content in the readme file, so I need to mark this as invalid. You can check out this template: https://github.com/microverseinc/readme-template

### Please submit a new code review once you are ready!

Good Luck and Happy Coding 

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

**Comment by pbkabali** [comment]
Hi @expjazz,

We appreciate your review and have worked on the feedback. Thanks again

**Review by expjazz — APPROVED** [review]
### Hey Team

## Great Job. The project is approved. :clap: 

#### Great use of the semantic HTML elements.  The design also looks really good!

The project passed all the requirements, but here are a few tips that would make it look even better. Remember that they are optional since the project already was approved: 

- [optional] The font-weight and colors look different from the original in the aside section :

Your clone
 :point_down: 

image

Original
:point_down: 
image

-[optional] I also noticed a high usage of ids. The problem here is that they need to be unique. Even that in your projects there were no repetitions, it can be tricky to keep track of them, and as bigger as the project grows, more difficult this task can be. It is better to use classes in this case.

### Congratulations on this project. You did great! Good luck with the next one! :pray: 

Happy Coding 

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

**Comment by pbkabali** [comment]
Thank you very much @expjazz for your time and beautiful insight. 
Your comments will undoubtedly help us improve our craft.

**Pull request merged**
